### PyTorch Tensors Introduction
A tensor is a data structure in the torch library that is similar to arrays

In [4]:
# Initializing a tensor from a python list
import torch
my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
# Get the shape of a tensor
tensor.shape

torch.Size([2, 3])

In [6]:
# Get the data type of a tensor
tensor.dtype

torch.int64

In [7]:
# When tensor shapes are compatible, you can do arithmetic operations on them
a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[3, 3], [4, 4]])

print(a + b)

tensor([[4, 4],
        [6, 6]])


In [10]:
# When tensor shapes are incompatible, you get an error
a = torch.tensor([[2, 2, 2], [4, 4, 4]])
b = torch.tensor([[3, 3]])
print(a + b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [12]:
# We can perform element-wise multiplication on tensors
a = torch.tensor([[2, 2, 2], [4, 4, 4]])
b = torch.tensor([[3, 3, 3], [5, 5, 5]])
print(torch.mul(a, b))
print(a * b)

tensor([[ 6,  6,  6],
        [20, 20, 20]])
tensor([[ 6,  6,  6],
        [20, 20, 20]])


In [14]:
# Matrix multiplication
a = torch.tensor([[2, 2], [4, 4]])
b = torch.tensor([[3, 3], [5, 5]])
print(torch.matmul(a, b))
print(a @ b)

tensor([[16, 16],
        [32, 32]])
tensor([[16, 16],
        [32, 32]])
